### ISSUE TITLE
I would like to have a beautiful Readme file. 

### ISSUE THREAD

**Issue by ZsuzsaMano** [ZsuzsaMano/ZoalNomad#1]
Would appreciate help to create an awesome readme file.

**Comment by bhantsi** [comment]
Hi I will like to work on this, please assign it to me

**Comment by ZsuzsaMano** [comment]
Thank  you

**Comment by ZsuzsaMano** [comment]
https://blog.bitsrc.io/how-to-write-beautiful-and-meaningful-readme-md-for-your-next-project-897045e3f991

I found this article really helpful. But I have to admit, I am quite a beginner with markdown

**Comment by anacarolinaarellano** [comment]
I will also work on this issue!

**Comment by ZsuzsaMano** [comment]
Thank you it is really amazing. How do you do the gif images?

**Comment by anacarolinaarellano** [comment]
I recorded my screen and then I converted those videos to gifs in a website

**Comment by ZsuzsaMano** [comment]
Thx, meanwhile I found a great gif recorder. Gifex. It's simple and has all
the features needed.

Ana Carolina Arellano <notifications@github.com> ezt írta (időpont: 2020.
okt. 14., Sze, 16:12):
